global using AutoMapper;
global using Delivires.Entities;
global using Delivires.UnitOfWorks;
global using Delivires.ViewModels;
global using Common.Controllers;
global using FluentValidation;
global using Common.EntityConfigurations;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.EntityFrameworkCore.Metadata.Builders;
global using Microsoft.AspNetCore.Mvc;
global using Common.Entites;
global using Common.Repositories;
global using Common.UnitOfWorks;
global using Delivires.Repositories;
global using Common.ViewModels;
global using Adresses.Enities;
global using Orders.Entities;
global using Categories.ViewModels;

